pygmentsuseclasses = true
baseurl = "http://netcell.github.io/"
copyright = "All rights reserved - 2016"
disqusshortname = "netcell"
languagecode = "en-us"
paginate = 5
pluralizelisttitles = false
theme = "netcell"
title = "@netcell"
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/"
weight = -120
[[menu.product]]
identifier = "phaser-inspector"
name = "Phaser Inspector"
url = "http://netcell.github.io/phaser-inspector"
weight = 1
[[menu.product]]
identifier = "phaser-nine-patch"
name = "Phaser Nine Patch"
url = "http://netcell.github.io/nine-patch-phaser-plugin"
weight = 2
[[menu.product]]
identifier = "netify"
name = "Netify"
url = "http://netcell.github.io/netify"
weight = 0
[params]
author = "netcell"
authorlocation = "Hanoi, Vietnam"
authorwebsite = "http://netcell.github.io"
bio = "Developer, jack of all trades and master of some."
cover = "img/bg.jpg"
description = "Romantic Programming..."
githubName = "netcell"
facebookName = "netcell"
googleAnalyticsUserID = "UA-62565835-4"
hideHUGOSupport = true
logo = "img/logo.jpg"
twitterName = "netcell"
RSSLink = "http://eepurl.com/bYfnUP"
[permalinks]
post = "/:year/:month/:filename/"
[sitemap]
ChangeFreq = ""
Filename = "sitemap.xml"
Priority = "-1"